### ISSUE TITLE
Unexpected error fetching Alpha Innotec data

### ISSUE THREAD

**Issue by w4iq3** [arjenbos/ha_alpha_innotec#31]
Just installed the integration, configured but it says 'No devices or entities'. Looking at the debug log it does get the data but after that an error shows.

Using HACS2.0, Core 2024.8.2

```
KeyError: 'modules'
2024-08-23 09:56:55.853 DEBUG (MainThread) [custom_components.alpha_innotec.coordinator] Finished fetching Alpha Innotec data in 2.931 seconds (success: False)
2024-08-23 09:56:55.854 ERROR (MainThread) [homeassistant.helpers.entity_platform] alpha_innotec raises exception ConfigEntryNotReady in forwarded platform binary_sensor; Instead raise ConfigEntryNotReady before calling async_forward_entry_setups
2024-08-23 09:56:55.929 DEBUG (SyncWorker_4) [custom_components.alpha_innotec.controller_api] [api/room/list] - response code: 200
2024-08-23 09:56:55.930 DEBUG (SyncWorker_4) [custom_components.alpha_innotec.controller_api] [api/room/list] - response body: {'success': True, 'message': '', 'loginRejected': False, 'groups': [{'groupid': 1, 'name': 'Begane Grond', 'rooms': [{'id': 1, 'appid': '01010002', 'actualTemperature': 21, 'isComfortMode': False, 'desiredTemperature': 20, 'roomstatus': 93, 'desiredTempDay': 20.5, 'desiredTempDay2': 20, 'desiredTempNight': 19.5, 'scheduleTempMin': 15, 'scheduleTempMax': 28, 'minTemperature': 19.5, 'maxTemperature': 28, 'cooling': True, 'coolingEnabled': True, 'imagepath': '/assets/images/room/default.png', 'name': 'Woonkamer', 'orderindex': 0, 'originalName': 'Woonkamer', 'status': 'ok', 'groupid': 1, 'windowPosition': 0}, {'id': 6, 'appid': '01060002', 'isComfortMode': False, 'desiredTemperature': 20, 'roomstatus': 121, 'desiredTempDay': 20, 'desiredTempDay2': 18, 'desiredTempNight': 18, 'scheduleTempMin': 15, 'scheduleTempMax': 28, 'minTemperature': 18, 'maxTemperature': 28, 'cooling': False, 'coolingEnabled': False, 'imagepath': '/assets/images/room/default.png', 'name': 'Dummy', 'orderindex': 6, 'originalName': 'Dummy', 'status': 'new', 'groupid': 1, 'windowPosition': 0}], 'orderindex': 1}, {'groupid': 2, 'name': '1e Verdieping', 'rooms': [{'id': 2, 'appid': '01020002', 'actualTemperature': 21.5, 'isComfortMode': False, 'desiredTemperature': 17, 'roomstatus': 134, 'desiredTempDay': 22.5, 'desiredTempDay2': 17, 'desiredTempNight': 16.5, 'scheduleTempMin': 15, 'scheduleTempMax': 28, 'minTemperature': 16.5, 'maxTemperature': 28, 'cooling': False, 'coolingEnabled': True, 'imagepath': '/assets/images/room/default.png', 'name': 'Badkamer', 'orderindex': 0, 'originalName': 'Badkamer', 'status': 'ok', 'groupid': 2, 'windowPosition': 0}, {'id': 3, 'appid': '01030002', 'actualTemperature': 21, 'isComfortMode': False, 'desiredTemperature': 16.5, 'roomstatus': 93, 'desiredTempDay': 17, 'desiredTempDay2': 16.5, 'desiredTempNight': 16, 'scheduleTempMin': 15, 'scheduleTempMax': 28, 'minTemperature': 16, 'maxTemperature': 28, 'cooling': True, 'coolingEnabled': True, 'imagepath': '/assets/images/room/default.png', 'name': 'Slaapkamer 1', 'orderindex': 1, 'originalName': 'Slaapkamer 1', 'status': 'ok', 'groupid': 2, 'windowPosition': 0}, {'id': 4, 'appid': '01040002', 'actualTemperature': 21, 'isComfortMode': False, 'desiredTemperature': 17, 'roomstatus': 93, 'desiredTempDay': 18, 'desiredTempDay2': 17, 'desiredTempNight': 16, 'scheduleTempMin': 15, 'scheduleTempMax': 28, 'minTemperature': 16, 'maxTemperature': 28, 'cooling': True, 'coolingEnabled': True, 'imagepath': '/assets/images/room/default.png', 'name': 'Slaapkamer 2', 'orderindex': 2, 'originalName': 'Slaapkamer 2', 'status': 'ok', 'groupid': 2, 'windowPosition': 0}, {'id': 5, 'appid': '01050002', 'actualTemperature': 20.5, 'isComfortMode': False, 'desiredTemperature': 17, 'roomstatus': 93, 'desiredTempDay': 18, 'desiredTempDay2': 17, 'desiredTempNight': 16, 'scheduleTempMin': 15, 'scheduleTempMax': 28, 'minTemperature': 16, 'maxTemperature': 28, 'cooling': True, 'coolingEnabled': True, 'imagepath': '/assets/images/room/default.png', 'name': 'Slaapkamer 3', 'orderindex': 3, 'originalName': 'Slaapkamer 3', 'status': 'ok', 'groupid': 2, 'windowPosition': 0}], 'orderindex': 1}], 'language': 'en', 'performance': 0.346}
2024-08-23 09:56:55.931 DEBUG (SyncWorker_4) [custom_components.alpha_innotec.controller_api] [api/room/list] - successfully fetched data from API
2024-08-23 09:56:55.940 ERROR (MainThread) [custom_components.alpha_innotec.coordinator] Unexpected error fetching Alpha Innotec data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alpha_innotec/coordinator.py", line 47, in _async_update_data
    for module_id in room_module['modules']:
                     ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'modules'
2024-08-23 09:56:55.941 DEBUG (MainThread) [custom_components.alpha_innotec.coordinator] Finished fetching Alpha Innotec data in 3.018 seconds (success: False)
2024-08-23 09:56:55.942 ERROR (MainThread) [homeassistant.helpers.entity_platform] alpha_innotec raises exception ConfigEntryNotReady in forwarded platform climate; Instead raise ConfigEntryNotReady before calling async_forward_entry_setups
```

**Comment by w4iq3** [comment]
Fixed it myself with some fiddling around and the use of ChatGPT, here's the full code for the coordinator.py file. It has something to do with the code that tries to get the room modules data.

```
import logging
from datetime import timedelta
from typing import Union, Optional

from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant
from homeassistant.helpers.update_coordinator import DataUpdateCoordinator

from . import ControllerAPI, GatewayAPI
from .const import DOMAIN, MODULE_TYPE_SENSOR
from .structs.Thermostat import Thermostat
from .structs.Valve import Valve

_LOGGER = logging.getLogger(__name__)

class AlphaInnotecCoordinator(DataUpdateCoordinator):

    data: dict[str, list[Union[Valve, Thermostat]]]

    def __init__(self, hass: HomeAssistant) -> None:
        """Initialize Alpha Innotec coordinator."""
        super().__init__(
            hass,
            _LOGGER,
            name="Alpha Innotec",
            update_interval=timedelta(seconds=60),
        )

        self.controller_api = hass.data[DOMAIN][self.config_entry.entry_id].get('controller_api')
        self.gateway_api = hass.data[DOMAIN][self.config_entry.entry_id].get('gateway_api')

    async def _async_update_data(self) -> dict[str, list[Union[Valve, Thermostat]]]:
        try:
            db_modules = await self.hass.async_add_executor_job(self.gateway_api.db_modules)
            all_modules = await self.hass.async_add_executor_job(self.gateway_api.all_modules)
            room_list = await self.hass.async_add_executor_job(self.controller_api.room_list)
        except Exception as e:
            _LOGGER.error("Failed to fetch module data: %s", e)
            return {}

        thermostats: list[Thermostat] = []
        valves: list[Valve] = []

        for room_id, room_module in all_modules.items():
            room = await self.hass.async_add_executor_job(self.controller_api.room_details, room_id, room_list)
            current_temperature: Optional[float] = None
            battery_percentage: Optional[float] = None

            for module_id in room_module.get('modules', []):
                if module_id not in db_modules.get('modules', {}):
                    continue

                module_details = db_modules['modules'][module_id]
                if module_details.get("type") == MODULE_TYPE_SENSOR:
                    current_temperature = module_details.get("currentTemperature")
                    battery_percentage = module_details.get("battery")

            if room.get('status', 'problem') == 'problem':
                _LOGGER.error("According to the API there is a problem with room: %s", room.get('name', 'Unknown'))

            thermostat = Thermostat(
                identifier=room_id,
                name=room.get('name', 'Unknown'),
                current_temperature=current_temperature,
                desired_temperature=room.get('desiredTemperature'),
                minimum_temperature=room.get('minTemperature'),
                maximum_temperature=room.get('maxTemperature'),
                cooling=room.get('cooling'),
                cooling_enabled=room.get('coolingEnabled'),
                battery_percentage=battery_percentage
            )

            thermostats.append(thermostat)

        for module_id, module in db_modules.get("modules", {}).items():
            if module.get("productId") != 3:
                continue

            for instance in module.get("instances", []):
                valve_id = '0' + instance.get('instance', '') + module.get('deviceid', '')[2:]
                used = any(valve_id in all_modules[room_id].get("modules", []) for room_id in all_modules)

                valve = Valve(
                    identifier=valve_id,
                    name=f"{module.get('name', 'Unknown')}-{instance.get('instance', '')}",
                    instance=instance.get("instance"),
                    device_id=module.get("deviceid"),
                    device_name=module.get("name", 'Unknown'),
                    status=instance.get("status"),
                    used=used
                )

                valves.append(valve)

        return {
            'valves': valves,
            'thermostats': thermostats
        }

```
